spring.application.name=api

# perfil dev (roda o seeder para teste do ranking) ou prod (nao roda o seeder)
spring.profiles.active=dev

# Conexao com o Banco (usando variaveis de ambiente)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Atualizacao automatica das tabelas pelo Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostra SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
api.security.token.secret=${API_TOKEN_SECRET}
server.error.include-message=always
